### read all emp 
GET http://localhost:3000/emp-api/emp 
###  read emp by id
GET http://localhost:3000/emp-api/emp/69ca17bb96194bba5f294a54
### display the emp info
POST http://localhost:3000/emp-api/emp
Content-Type: application/json 

{
   "name":"vinya",
   "email":"vinya123@gmail.com",
   "mobile":"phone",
   "designation":"manager",
   "companyName":"vinyareddy"
   
}
### modify the emp
PUT http://localhost:3000/emp-api/emp/69cb8cf9a1060d004c85432d
Content-Type: application/json 

{
   "name":"vidya",
   "email":"vidya@gmail.com",
   "mobile":"phone",
   "designation":"manager",
   "companyName":"flipkart"
}

### delete the user 

DELETE  http://localhost:3000/emp-api/emp/69ca2c6c5b7f67ecd7ad3a09






